### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by benkeser** [lpf057810/final_project_docker#1]
You have issues with your Makefile. Please see hints given via Canvas announcement and carefully review. Also please `git rm` the compiled report from the `report/` subfolder on github. 

I will re-grade when this issue is closed (or when assignment is due, whichever is first).

**Comment by lpf057810** [comment]
project_image: Dockerfile $(PROJECTFILES) $(RENVFILES)
report/report.html: project_image 
	docker run -v "/$$(pwd)/report":/project/report lpf057810/project_image:latest

Thank you Professor! I have updated my Makefile
